Improved to accept null values
Mk-Chan/chessbot pull request #3
Opened 2019-10-17 16:39 UTC by Tempate

2019-10-19 15:59 UTC, Mk-Chan requested changes

2019-10-19 15:59 UTC, Mk-Chan commented on commands/match.py
> +        mu_max = min(m_mu + phi_inv(0.975) * m_std_dev, np.nextafter(1,0))
Can't you make do without numpy? I'd prefer not adding an extra dependency. Also formatting (There should be a space after the comma)

2019-10-20 07:56 UTC, Tempate commented on commands/match.py
> +        mu_max = min(m_mu + phi_inv(0.975) * m_std_dev, np.nextafter(1,0))
Done!

2019-10-20 08:39 UTC, Mk-Chan commented
```
commands/match.py", line 25
    if wins < 0 or losses < 0 or draws < 0:
                                          ^
```
That's cuz you used tabs instead of spaces. That's ok, I'll fix it

2019-10-20 08:45 UTC, merged

2019-10-20 08:45 UTC, Mk-Chan commented
Thanks

2019-10-20 12:07 UTC, Mk-Chan commented
This commit doesn't work the error bar is screwed. Force pushed out.